# Generated by Django 5.1.1 on 2024-11-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='book_post/upload_book_img')),
                ('BookPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BooCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BooCategory', to='category.category')),
            ],
        ),
    ]
