# Generated by Django 5.1.1 on 2024-11-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='BooCategory',
            new_name='Category',
        ),
    ]
