# Generated by Django 5.1.1 on 2024-11-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_post', '0004_alter_book_image'),
        ('category', '0003_rename_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Category',
        ),
        migrations.AddField(
            model_name='book',
            name='Category',
            field=models.ManyToManyField(related_name='BookCategory', to='category.category'),
        ),
    ]
