# Generated by Django 5.1.1 on 2024-11-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_post', '0014_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
